##################################################
# TxHISCentralRegistry_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.ServiceModuleWriter
#
##################################################

from TxHISCentralRegistry_services import *
from ZSI.ServiceContainer import ServiceSOAPBinding

class TxHISCentralRegistry(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?>
<wsdl:definitions name=\"TxHISCentralRegistry\" targetNamespace=\"http://greylin/TxHISCentralRegistry/\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:tns=\"http://greylin/TxHISCentralRegistry/\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">
  <wsdl:types>
    <xsd:schema targetNamespace=\"http://greylin/TxHISCentralRegistry/\">
      <xsd:element name=\"GetSourcesGEMSS\">
        <xsd:complexType>
          <xsd:sequence>

          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name=\"GetSourcesGEMSSResponse\">
        <xsd:complexType>
                    <xsd:annotation>
                    	<xsd:documentation>This is the return type of GetServiceDetails operation. Baisically, it's main message load is  an array of ServiceDetail objects.</xsd:documentation>
                    </xsd:annotation>
                    <xsd:sequence>
          	<xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"ServiceDetail\" nillable=\"false\" type=\"tns:ServiceDetail\">
          		<xsd:annotation>
          			<xsd:documentation>The GetServiceDetails function would return an array of ServiceDetail object, and each ServiceDetail object is corresponding to one unique network (data source).

Details:
This array could be empty, eventhough in reality it won't, because its backend database won't be empty.
The length of this array could potentially be unlimited, eventhough it will have at most 30+- networks/datasets.
</xsd:documentation>
          		</xsd:annotation></xsd:element>

          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    
      <xsd:complexType name=\"ServiceDetail\">
      	<xsd:annotation>
      		<xsd:documentation>
      			ServiceDetail consists detailed information about a
      			unique network/datasource, including:

      			SourceURL: A string, indicating any ODM WaterML URL
      			SourceNetworkName: A string, indicating Network name
      			of interest on the SourceURL UpdateFrequencyType: A
      			string, enforced by enumeration of 4 possible types:
      			Daily, Weekly, Monthly, Adhoc UpdateFrequencyValue: A
      			string, can be ..., if the update frequency type is
      			Daily or Monday - Suday if the update frequency type
      			is Weekly or 1st - 31st if the update frequency type
      			is Monthly or a specific date, if the update frequency
      			type is Adhoc, respectively. SourceParameterCodes: An
      			array of string. Each string indicates an available
      			parametercode for this particular network.
      		</xsd:documentation>
      	</xsd:annotation>
      	<xsd:sequence>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"RemoteSourceURL\" nillable=\"false\" type=\"xsd:string\">
      			<xsd:annotation>
      				<xsd:documentation>
      					An ODM WaterML web service WSDL URL. Each
      					network has a unique one ?
      				</xsd:documentation>
      			</xsd:annotation>
      		</xsd:element>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"SourceFormat\" type=\"xsd:string\"/>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"RemoteSourceNetWorkName\" type=\"xsd:string\">
      			<xsd:annotation>
      				<xsd:documentation>
      					Network name of interest on the source URL.
      				</xsd:documentation>
      			</xsd:annotation>
      		</xsd:element>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"UpdateFrequencyType\">

      			<xsd:simpleType>
      				<xsd:annotation>
      					<xsd:documentation>
      						UpdateFrequencyType, a string can be any
      						of the 4 values: Daily, Weekly, Monthly,
      						Ad-Hoc
      					</xsd:documentation>
      				</xsd:annotation>
      				<xsd:restriction base=\"xsd:string\">


      					<xsd:enumeration value=\"Daily\"/>
      					<xsd:enumeration value=\"Weekly\"/>
      					<xsd:enumeration value=\"Monthly\"/>


      					<xsd:enumeration value=\"Ad-Hoc\"/>
      				</xsd:restriction>
      			</xsd:simpleType>
      		</xsd:element>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"UpdateFrequencyValue\" type=\"xsd:string\">
      			<xsd:annotation>
      				<xsd:documentation>
      					UpdateFrequencyValue: A string, can be ..., if
      					the update frequency type is Daily (may be a
      					time?) or Monday - Suday if the update
      					frequency type is Weekly or 1st - 31st if the
      					update frequency type is Monthly or a specific
      					date, if the update frequency type is Adhoc,
      					respectively.
      				</xsd:documentation>
      			</xsd:annotation>
      		</xsd:element>

      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"SourceSummarizedDescription\" type=\"xsd:string\">
      		</xsd:element>

      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"SourceDescriptionLink\" type=\"xsd:string\">
      		</xsd:element>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"SourceLogoLink\" type=\"xsd:string\">
      		</xsd:element>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"RemoteSourceParameterCodes\" type=\"tns:SourceParameterCodesType\">
      			<xsd:annotation>
      				<xsd:documentation>
      					This is an array of parameter codes that
      					corresponds to the source URL. notice this
      					array must exist, yet its number of
      					subelements (SourceParameterCodes) can be
      					potentially 0.
      				</xsd:documentation>
      			</xsd:annotation>
      		</xsd:element>
      	</xsd:sequence>
      </xsd:complexType>
    
      <xsd:complexType name=\"SourceParameterCodesType\">
                <xsd:annotation>
                	<xsd:documentation>An array of parameter codes that corresponds to the SourceURL.
Notice this array can have potentially unlimite number of actual parameter code.</xsd:documentation>
                </xsd:annotation>
                <xsd:sequence>
      		<xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"SourceParameterCode\" type=\"xsd:string\">
      			<xsd:annotation>
      				<xsd:documentation>A String indicating an available parameter code (remote side)  for a this network/datasource.</xsd:documentation>
      			</xsd:annotation></xsd:element>
      	</xsd:sequence>
      </xsd:complexType>
      <xsd:element name=\"GetTXHISConvertedOutputGEMSS\">
      	<xsd:complexType>
      		<xsd:sequence>

      			<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"RemoteSourceURL\" nillable=\"false\" type=\"xsd:string\">
      				<xsd:annotation>
      					<xsd:documentation>A string indicating a Source's WSDL address URL.</xsd:documentation>
      				</xsd:annotation></xsd:element>
      			<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"RemoteSourceNetworkName\" nillable=\"false\" type=\"xsd:string\">
                            <xsd:annotation>
                            	<xsd:documentation>A string indicating the name of a unique NetworkName.</xsd:documentation>
                            </xsd:annotation>
      			</xsd:element>

                        <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"RemoteSourceParameterCode\" nillable=\"false\" type=\"xsd:string\">
                            <xsd:annotation>
                            	<xsd:documentation>A string indicating the Remoteside Parameter Code.</xsd:documentation>
                            </xsd:annotation>
      			</xsd:element>
                        <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"RemoteValues\" nillable=\"false\" type=\"tns:ValuesArray\">
      				<xsd:annotation>
      					<xsd:documentation>An array of raw values from the Remote site (WaterML call).
</xsd:documentation>
      				</xsd:annotation></xsd:element>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
      <xsd:element name=\"GetTXHISConvertedOutputGEMSSResponse\">
      	<xsd:complexType>
      		<xsd:sequence>






      			<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"TXHISResponseObj\" type=\"tns:TXHISResponseObjType\">
      				<xsd:annotation>
      					<xsd:documentation>Return a so-called string to accomodate C#'s need of &quot;object&quot;.</xsd:documentation>
      				</xsd:annotation></xsd:element>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
    
      <xsd:complexType name=\"ValuesArray\">
      	<xsd:sequence>
      		<xsd:element maxOccurs=\"1000\" minOccurs=\"1\" name=\"value\" type=\"xsd:float\"/>
      	</xsd:sequence>
      </xsd:complexType>
      <xsd:element name=\"GetConvertedOutputFault\">
      	<xsd:complexType>
      		<xsd:sequence>

      			<xsd:element name=\"GetConvertedOutputFault\" type=\"xsd:string\">
      			</xsd:element>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
    
      <xsd:complexType name=\"TXHISResponseObjType\">
      	<xsd:sequence>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"TXHISParameterName\" type=\"xsd:string\">

      		</xsd:element>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"TXHISParameterCode\" type=\"xsd:string\">
      		</xsd:element>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"TXHISParameterDescription\" type=\"xsd:string\">
      		</xsd:element>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"TXHISParameterUnit\" type=\"xsd:string\">
      		</xsd:element>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"TXHISParameterUnitDescription\" type=\"xsd:string\">
      		</xsd:element>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"TXHISParameterValues\" type=\"tns:ValuesArray\"/>
      	</xsd:sequence>
      </xsd:complexType>
      <xsd:element name=\"GetTXHISParameters\">
      	<xsd:complexType>
      		<xsd:sequence>

      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
      <xsd:element name=\"GetTXHISParametersResponse\">
      	<xsd:complexType>
      		<xsd:sequence>

      			<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"ParameterList\" type=\"tns:ParameterArray\"/>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
    
      <xsd:complexType name=\"ParameterArray\">
      	<xsd:sequence>
      		<xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"ParameterInstance\" type=\"tns:ParameterInfo\"/>
      	</xsd:sequence>
      </xsd:complexType>
    
      <xsd:complexType name=\"ParameterInfo\">
      	<xsd:sequence>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"ParameterCode\" type=\"xsd:string\"/>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"ParameterName\" type=\"xsd:string\"/>
      	</xsd:sequence>
      </xsd:complexType>
      <xsd:element name=\"GetRemoteParameterCode\">
      	<xsd:complexType>
      		<xsd:sequence>

      			<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"SourceNetworkName\" type=\"xsd:string\">
      			</xsd:element>
      			<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"TXHISParameterCode\" type=\"xsd:string\">
      			</xsd:element>
      			<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"WSDLLink\" type=\"xsd:string\"/>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
      <xsd:element name=\"GetRemoteParameterCodeResponse\">
      	<xsd:complexType>
      		<xsd:sequence>

      			<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"RemoteParameterCode\" type=\"xsd:string\"/>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
      <xsd:element name=\"GetHISParamAvailableSources\">
      	<xsd:complexType>
      		<xsd:sequence>

      			<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"HISParamCode\" type=\"xsd:string\"/>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
      <xsd:element name=\"GetHISParamAvailableSourcesResponse\">
      	<xsd:complexType>
      		<xsd:sequence>

      			<xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"SourceWithParamCodeInstance\" type=\"tns:SourceWithRemoteParamCode\"/>
      		</xsd:sequence>
      	</xsd:complexType>
      </xsd:element>
    
      <xsd:complexType name=\"SourceWithRemoteParamCode\">
      	<xsd:sequence>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"WSDLLink\" type=\"xsd:string\"/>
      		<xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"SourceName\" type=\"xsd:string\"/>
      		<xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"RemoteParamCode\" type=\"xsd:string\"/>
      	</xsd:sequence>
      </xsd:complexType>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name=\"GetSourcesGEMSSRequest\">
    <wsdl:part element=\"tns:GetSourcesGEMSS\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetSourcesGEMSSResponse\">
    <wsdl:part element=\"tns:GetSourcesGEMSSResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetTXHISConvertedOutputGEMSSRequest\">
  	<wsdl:part element=\"tns:GetTXHISConvertedOutputGEMSS\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetTXHISConvertedOutputGEMSSResponse\">
  	<wsdl:part element=\"tns:GetTXHISConvertedOutputGEMSSResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetConvertedOutputFault\">
  	<wsdl:part element=\"tns:GetConvertedOutputFault\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetTXHISParametersRequest\">
  	<wsdl:part element=\"tns:GetTXHISParameters\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetTXHISParametersResponse\">
  	<wsdl:part element=\"tns:GetTXHISParametersResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetRemoteParameterCodeRequest\">
  	<wsdl:part element=\"tns:GetRemoteParameterCode\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetRemoteParameterCodeResponse\">
  	<wsdl:part element=\"tns:GetRemoteParameterCodeResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetHISParamAvailableSourcesRequest\">
  	<wsdl:part element=\"tns:GetHISParamAvailableSources\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetHISParamAvailableSourcesResponse\">
  	<wsdl:part element=\"tns:GetHISParamAvailableSourcesResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:portType name=\"TxHISCentralRegistry\">
    <wsdl:operation name=\"GetSourcesGEMSS\">
      <wsdl:input message=\"tns:GetSourcesGEMSSRequest\"/>
      <wsdl:output message=\"tns:GetSourcesGEMSSResponse\"/>
    </wsdl:operation>
    <wsdl:operation name=\"GetTXHISConvertedOutputGEMSS\">
    	<wsdl:input message=\"tns:GetTXHISConvertedOutputGEMSSRequest\"/>
    	<wsdl:output message=\"tns:GetTXHISConvertedOutputGEMSSResponse\"/>
        </wsdl:operation>
    <wsdl:operation name=\"GetTXHISParameters\">
    	<wsdl:input message=\"tns:GetTXHISParametersRequest\"/>
    	<wsdl:output message=\"tns:GetTXHISParametersResponse\"/>
    </wsdl:operation>
    <wsdl:operation name=\"GetRemoteParameterCode\">
    	<wsdl:input message=\"tns:GetRemoteParameterCodeRequest\"/>
    	<wsdl:output message=\"tns:GetRemoteParameterCodeResponse\"/>
    </wsdl:operation>
    <wsdl:operation name=\"GetHISParamAvailableSources\">
    	<wsdl:input message=\"tns:GetHISParamAvailableSourcesRequest\"/>
    	<wsdl:output message=\"tns:GetHISParamAvailableSourcesResponse\"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name=\"TxHISCentralRegistrySOAP\" type=\"tns:TxHISCentralRegistry\">

  	<soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
  	<wsdl:operation name=\"GetSourcesGEMSS\">

  		<soap:operation soapAction=\"http://greylin/TxHISCentralRegistry/GetSourcesGEMSS\"/>
  		<wsdl:input>

  			<soap:body use=\"literal\"/>
  		</wsdl:input>
  		<wsdl:output>

  			<soap:body use=\"literal\"/>
  		</wsdl:output>
  	</wsdl:operation>
  	<wsdl:operation name=\"GetTXHISConvertedOutputGEMSS\">

  		<soap:operation soapAction=\"http://greylin/TxHISCentralRegistry/GetTXHISConvertedOutputGEMSS\"/>
  		<wsdl:input>

  			<soap:body use=\"literal\"/>
  		</wsdl:input>
  		<wsdl:output>

  			<soap:body use=\"literal\"/>
  		</wsdl:output>
  	</wsdl:operation>
  	<wsdl:operation name=\"GetTXHISParameters\">

  		<soap:operation soapAction=\"http://greylin/TxHISCentralRegistry/GetTXHISParameters\"/>
  		<wsdl:input>

  			<soap:body use=\"literal\"/>
  		</wsdl:input>
  		<wsdl:output>

  			<soap:body use=\"literal\"/>
  		</wsdl:output>
  	</wsdl:operation>
  	<wsdl:operation name=\"GetRemoteParameterCode\">

  		<soap:operation soapAction=\"http://greylin/TxHISCentralRegistry/GetRemoteParameterCode\"/>
  		<wsdl:input>

  			<soap:body use=\"literal\"/>
  		</wsdl:input>
  		<wsdl:output>

  			<soap:body use=\"literal\"/>
  		</wsdl:output>
  	</wsdl:operation>
  	<wsdl:operation name=\"GetHISParamAvailableSources\">
  		<soap:operation soapAction=\"http://greylin/TxHISCentralRegistry/GetHISParamAvailableSources\"/>
  		<wsdl:input>
  			<soap:body use=\"literal\"/>
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body use=\"literal\"/>
  		</wsdl:output>
  	</wsdl:operation>
  </wsdl:binding>

  <wsdl:service name=\"TxHISCentralRegistry\">
    <wsdl:port binding=\"tns:TxHISCentralRegistrySOAP\" name=\"TxHISCentralRegistrySOAP\">
      <soap:address location=\"http://greylin:9080/HISCentralService\"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>"""

    def __init__(self, post='/HISCentralService', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_GetSourcesGEMSS(self, ps):
        self.request = ps.Parse(GetSourcesGEMSSRequest.typecode)
        return GetSourcesGEMSSResponse()

    soapAction['http://greylin/TxHISCentralRegistry/GetSourcesGEMSS'] = 'soap_GetSourcesGEMSS'
    root[(GetSourcesGEMSSRequest.typecode.nspname,GetSourcesGEMSSRequest.typecode.pname)] = 'soap_GetSourcesGEMSS'

    def soap_GetTXHISConvertedOutputGEMSS(self, ps):
        self.request = ps.Parse(GetTXHISConvertedOutputGEMSSRequest.typecode)
        return GetTXHISConvertedOutputGEMSSResponse()

    soapAction['http://greylin/TxHISCentralRegistry/GetTXHISConvertedOutputGEMSS'] = 'soap_GetTXHISConvertedOutputGEMSS'
    root[(GetTXHISConvertedOutputGEMSSRequest.typecode.nspname,GetTXHISConvertedOutputGEMSSRequest.typecode.pname)] = 'soap_GetTXHISConvertedOutputGEMSS'

    def soap_GetTXHISParameters(self, ps):
        self.request = ps.Parse(GetTXHISParametersRequest.typecode)
        return GetTXHISParametersResponse()

    soapAction['http://greylin/TxHISCentralRegistry/GetTXHISParameters'] = 'soap_GetTXHISParameters'
    root[(GetTXHISParametersRequest.typecode.nspname,GetTXHISParametersRequest.typecode.pname)] = 'soap_GetTXHISParameters'

    def soap_GetRemoteParameterCode(self, ps):
        self.request = ps.Parse(GetRemoteParameterCodeRequest.typecode)
        return GetRemoteParameterCodeResponse()

    soapAction['http://greylin/TxHISCentralRegistry/GetRemoteParameterCode'] = 'soap_GetRemoteParameterCode'
    root[(GetRemoteParameterCodeRequest.typecode.nspname,GetRemoteParameterCodeRequest.typecode.pname)] = 'soap_GetRemoteParameterCode'

    def soap_GetHISParamAvailableSources(self, ps):
        self.request = ps.Parse(GetHISParamAvailableSourcesRequest.typecode)
        return GetHISParamAvailableSourcesResponse()

    soapAction['http://greylin/TxHISCentralRegistry/GetHISParamAvailableSources'] = 'soap_GetHISParamAvailableSources'
    root[(GetHISParamAvailableSourcesRequest.typecode.nspname,GetHISParamAvailableSourcesRequest.typecode.pname)] = 'soap_GetHISParamAvailableSources'

