################################################## 
# TxHISCentralRegistry_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from TxHISCentralRegistry_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class TxHISCentralRegistryLocator:
    TxHISCentralRegistry_address = "http://greylin.twdb.state.tx.us:9080/TXHISCentralService"
    def getTxHISCentralRegistryAddress(self):
        return TxHISCentralRegistryLocator.TxHISCentralRegistry_address
    def getTxHISCentralRegistry(self, url=None, **kw):
        return TxHISCentralRegistrySOAPSOAP(url or TxHISCentralRegistryLocator.TxHISCentralRegistry_address, **kw)

# Methods
class TxHISCentralRegistrySOAPSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: GetSourcesGEMSS
    def GetSourcesGEMSS(self, request):
        if isinstance(request, GetSourcesGEMSSRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://greylin/TxHISCentralRegistry/GetSourcesGEMSS", **kw)
        # no output wsaction
        response = self.binding.Receive(GetSourcesGEMSSResponse.typecode)
        return response

    # op: GetTXHISConvertedOutputGEMSS
    def GetTXHISConvertedOutputGEMSS(self, request):
        if isinstance(request, GetTXHISConvertedOutputGEMSSRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://greylin/TxHISCentralRegistry/GetTXHISConvertedOutputGEMSS", **kw)
        # no output wsaction
        response = self.binding.Receive(GetTXHISConvertedOutputGEMSSResponse.typecode)
        return response

GetSourcesGEMSSRequest = ns0.GetSourcesGEMSS_Dec().pyclass

GetSourcesGEMSSResponse = ns0.GetSourcesGEMSSResponse_Dec().pyclass

GetTXHISConvertedOutputGEMSSRequest = ns0.GetTXHISConvertedOutputGEMSS_Dec().pyclass

GetTXHISConvertedOutputGEMSSResponse = ns0.GetTXHISConvertedOutputGEMSSResponse_Dec().pyclass
