##################################################
# WaterOneFlow_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.ServiceModuleWriter
#
##################################################

from WaterOneFlow_services import *
from ZSI.fault import Fault, ZSIFaultDetail
from ZSI.ServiceContainer import ServiceSOAPBinding

class WaterOneFlow(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?>
<wsdl:definitions targetNamespace=\"http://www.cuahsi.org/his/1.0/ws/\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http/\" xmlns:mime=\"http://schemas.xmlsoap.org/wsdl/mime/\" xmlns:s=\"http://www.w3.org/2001/XMLSchema\" xmlns:s1=\"http://www.cuahsi.org/waterML/1.0/\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:soap12=\"http://schemas.xmlsoap.org/wsdl/soap12/\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:tm=\"http://microsoft.com/wsdl/mime/textMatching/\" xmlns:tns=\"http://www.cuahsi.org/his/1.0/ws/\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">
  <wsdl:documentation xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">&lt;div&gt;&lt;strong&gt;Developmental service. This service is internal CUAHSI use, and evaluation.&lt;/strong&gt;&lt;/div&gt;</wsdl:documentation>
  <wsdl:types>
    <s:schema elementFormDefault=\"qualified\" targetNamespace=\"http://www.cuahsi.org/his/1.0/ws/\">
      <s:import namespace=\"http://www.cuahsi.org/waterML/1.0/\"/>
      <s:element name=\"GetSitesXml\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"site\" type=\"tns:ArrayOfString\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"authToken\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name=\"ArrayOfString\">
        <s:sequence>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"string\" nillable=\"true\" type=\"s:string\"/>
        </s:sequence>
      </s:complexType>
      <s:element name=\"GetSitesXmlResponse\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"GetSitesXmlResult\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetSiteInfo\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"site\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"authToken\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetSiteInfoResponse\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"GetSiteInfoResult\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetVariableInfo\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variable\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"authToken\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetVariableInfoResponse\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"GetVariableInfoResult\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetSites\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"site\" type=\"tns:ArrayOfString\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"authToken\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetSitesResponse\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" ref=\"s1:sitesResponse\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetSiteInfoObject\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"site\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"authToken\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetSiteInfoObjectResponse\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" ref=\"s1:sitesResponse\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetVariableInfoObject\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variable\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"authToken\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetVariableInfoObjectResponse\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" ref=\"s1:variablesResponse\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetValues\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"location\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variable\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"startDate\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"endDate\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"authToken\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetValuesResponse\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"GetValuesResult\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetValuesObject\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"location\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variable\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"startDate\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"endDate\" type=\"s:string\"/>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"authToken\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetValuesObjectResponse\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" ref=\"s1:timeSeriesResponse\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
    </s:schema>
    <s:schema elementFormDefault=\"qualified\" targetNamespace=\"http://www.cuahsi.org/waterML/1.0/\">
      <s:element name=\"sitesResponse\" type=\"s1:SiteInfoResponseType\"/>
      <s:complexType name=\"SiteInfoResponseType\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"queryInfo\" type=\"s1:QueryInfoType\"/>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"site\">
            <s:complexType>
              <s:sequence>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"siteInfo\" type=\"s1:SiteInfoType\"/>
                <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"seriesCatalog\" type=\"s1:seriesCatalogType\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"extension\"/>
              </s:sequence>
            </s:complexType>
          </s:element>
        </s:sequence>
      </s:complexType>
      <s:complexType name=\"QueryInfoType\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"creationTime\" type=\"s:dateTime\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"queryURL\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"querySQL\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"criteria\">
            <s:complexType>
              <s:sequence>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"locationParam\" type=\"s:string\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variableParam\" type=\"s:string\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"timeParam\">
                  <s:complexType>
                    <s:sequence>
                      <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"beginDateTime\" type=\"s:string\"/>
                      <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"endDateTime\" type=\"s:string\"/>
                    </s:sequence>
                  </s:complexType>
                </s:element>
              </s:sequence>
            </s:complexType>
          </s:element>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"note\">
            <s:complexType>
              <s:simpleContent>
                <s:extension base=\"s:string\">
                  <s:attribute name=\"type\" type=\"s:string\"/>
                  <s:attribute name=\"href\" type=\"s:string\"/>
                  <s:attribute name=\"title\" type=\"s:string\"/>
                  <s:attribute name=\"show\" type=\"s:string\"/>
                </s:extension>
              </s:simpleContent>
            </s:complexType>
          </s:element>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"extension\"/>
        </s:sequence>
      </s:complexType>
      <s:complexType name=\"SiteInfoType\">
        <s:complexContent mixed=\"false\">
          <s:extension base=\"s1:SourceInfoType\">
            <s:sequence>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"siteName\" type=\"s:string\"/>
              <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"siteCode\">
                <s:complexType>
                  <s:simpleContent>
                    <s:extension base=\"s:string\">
                      <s:attribute name=\"defaultId\" type=\"s:boolean\"/>
                      <s:attribute name=\"network\" type=\"s:normalizedString\"/>
                      <s:attribute name=\"siteID\" type=\"s:normalizedString\"/>
                    </s:extension>
                  </s:simpleContent>
                </s:complexType>
              </s:element>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"timeZoneInfo\">
                <s:complexType>
                  <s:sequence>
                    <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"defaultTimeZone\" nillable=\"true\">
                      <s:complexType>
                        <s:attribute name=\"ZoneAbbreviation\" type=\"s:normalizedString\"/>
                        <s:attribute name=\"ZoneOffset\" type=\"s:string\"/>
                      </s:complexType>
                    </s:element>
                    <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"daylightSavingsTimeZone\" nillable=\"true\">
                      <s:complexType>
                        <s:attribute name=\"ZoneAbbreviation\" type=\"s:normalizedString\"/>
                        <s:attribute name=\"ZoneOffset\" type=\"s:string\"/>
                      </s:complexType>
                    </s:element>
                  </s:sequence>
                </s:complexType>
              </s:element>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"geoLocation\">
                <s:complexType>
                  <s:sequence>
                    <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"geogLocation\" type=\"s1:GeogLocationType\"/>
                    <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"localSiteXY\">
                      <s:complexType>
                        <s:sequence>
                          <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"X\" type=\"s:double\"/>
                          <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"Y\" type=\"s:double\"/>
                          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Z\" type=\"s:double\"/>
                          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"note\">
                            <s:complexType>
                              <s:simpleContent>
                                <s:extension base=\"s:string\">
                                  <s:attribute name=\"type\" type=\"s:string\"/>
                                  <s:attribute name=\"href\" type=\"s:string\"/>
                                  <s:attribute name=\"title\" type=\"s:string\"/>
                                  <s:attribute name=\"show\" type=\"s:string\"/>
                                </s:extension>
                              </s:simpleContent>
                            </s:complexType>
                          </s:element>
                        </s:sequence>
                        <s:attribute name=\"projectionInformation\" type=\"s:string\"/>
                      </s:complexType>
                    </s:element>
                  </s:sequence>
                </s:complexType>
              </s:element>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"elevation_m\" type=\"s:double\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"verticalDatum\" type=\"s:string\"/>
              <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"note\">
                <s:complexType>
                  <s:simpleContent>
                    <s:extension base=\"s:string\">
                      <s:attribute name=\"type\" type=\"s:string\"/>
                      <s:attribute name=\"href\" type=\"s:string\"/>
                      <s:attribute name=\"title\" type=\"s:string\"/>
                      <s:attribute name=\"show\" type=\"s:string\"/>
                    </s:extension>
                  </s:simpleContent>
                </s:complexType>
              </s:element>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"extension\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"altname\"/>
            </s:sequence>
            <s:attribute name=\"oid\" type=\"s:normalizedString\"/>
            <s:attribute name=\"metadataDateTime\" type=\"s:dateTime\"/>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name=\"SourceInfoType\"/>
      <s:complexType name=\"DataSetInfoType\">
        <s:complexContent mixed=\"false\">
          <s:extension base=\"s1:SourceInfoType\">
            <s:sequence>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"dataSetIdentifier\" type=\"s:string\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"timeZoneInfo\">
                <s:complexType>
                  <s:sequence>
                    <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"defaultTimeZone\" nillable=\"true\">
                      <s:complexType>
                        <s:attribute name=\"ZoneAbbreviation\" type=\"s:normalizedString\"/>
                        <s:attribute name=\"ZoneOffset\" type=\"s:string\"/>
                      </s:complexType>
                    </s:element>
                    <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"daylightSavingsTimeZone\" nillable=\"true\">
                      <s:complexType>
                        <s:attribute name=\"ZoneAbbreviation\" type=\"s:normalizedString\"/>
                        <s:attribute name=\"ZoneOffset\" type=\"s:string\"/>
                      </s:complexType>
                    </s:element>
                  </s:sequence>
                </s:complexType>
              </s:element>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"dataSetDescription\" type=\"s:string\"/>
              <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"note\">
                <s:complexType>
                  <s:simpleContent>
                    <s:extension base=\"s:string\">
                      <s:attribute name=\"type\" type=\"s:string\"/>
                      <s:attribute name=\"href\" type=\"s:string\"/>
                      <s:attribute name=\"title\" type=\"s:string\"/>
                      <s:attribute name=\"show\" type=\"s:string\"/>
                    </s:extension>
                  </s:simpleContent>
                </s:complexType>
              </s:element>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"dataSetLocation\" type=\"s1:GeogLocationType\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"extension\"/>
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name=\"GeogLocationType\">
        <s:attribute default=\"EPSG:4326\" name=\"srs\" type=\"s:string\"/>
      </s:complexType>
      <s:complexType name=\"LatLonBoxType\">
        <s:complexContent mixed=\"false\">
          <s:extension base=\"s1:GeogLocationType\">
            <s:sequence>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"south\" type=\"s:double\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"west\" type=\"s:double\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"north\" type=\"s:double\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"east\" type=\"s:double\"/>
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name=\"LatLonPointType\">
        <s:complexContent mixed=\"false\">
          <s:extension base=\"s1:GeogLocationType\">
            <s:sequence>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"latitude\" type=\"s:double\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"longitude\" type=\"s:double\"/>
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name=\"seriesCatalogType\">
        <s:sequence>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"note\">
            <s:complexType>
              <s:simpleContent>
                <s:extension base=\"s:string\">
                  <s:attribute name=\"type\" type=\"s:string\"/>
                  <s:attribute name=\"href\" type=\"s:string\"/>
                  <s:attribute name=\"title\" type=\"s:string\"/>
                  <s:attribute name=\"show\" type=\"s:string\"/>
                </s:extension>
              </s:simpleContent>
            </s:complexType>
          </s:element>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"series\">
            <s:complexType>
              <s:sequence>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"dataType\" type=\"s1:dataTypeEnum\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variable\" type=\"s1:VariableInfoType\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"valueCount\">
                  <s:complexType>
                    <s:simpleContent>
                      <s:extension base=\"s:int\">
                        <s:attribute name=\"countIsEstimated\" type=\"s:boolean\"/>
                      </s:extension>
                    </s:simpleContent>
                  </s:complexType>
                </s:element>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variableTimeInterval\" type=\"s1:TimePeriodType\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"valueType\" type=\"s1:valueTypeEnum\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"generalCategory\" type=\"s1:generalCategoryEnum\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"sampleMedium\" type=\"s1:SampleMediumEnum\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Method\" type=\"s1:MethodType\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Source\" type=\"s1:SourceType\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"QualityControlLevel\" nillable=\"true\" type=\"s1:QualityControlLevelType\"/>
              </s:sequence>
            </s:complexType>
          </s:element>
        </s:sequence>
        <s:attribute name=\"menuGroupName\" type=\"s:string\"/>
        <s:attribute name=\"serviceWsdl\" type=\"s:anyURI\"/>
      </s:complexType>
      <s:simpleType name=\"dataTypeEnum\">
        <s:restriction base=\"s:string\">
          <s:enumeration value=\"Continuous\"/>
          <s:enumeration value=\"Instantaneous\"/>
          <s:enumeration value=\"Cumulative\"/>
          <s:enumeration value=\"Incremental\"/>
          <s:enumeration value=\"Average\"/>
          <s:enumeration value=\"Maximum\"/>
          <s:enumeration value=\"Minimum\"/>
          <s:enumeration value=\"Constant Over Interval\"/>
          <s:enumeration value=\"Categorical\"/>
          <s:enumeration value=\"Best Easy Systematic Estimator \"/>
        </s:restriction>
      </s:simpleType>
      <s:complexType name=\"VariableInfoType\">
        <s:sequence>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"variableCode\">
            <s:complexType>
              <s:simpleContent>
                <s:extension base=\"s:token\">
                  <s:attribute name=\"network\" type=\"s:string\"/>
                  <s:attribute name=\"vocabulary\" type=\"s:string\"/>
                  <s:attribute name=\"default\" type=\"s:boolean\"/>
                  <s:attribute name=\"variableID\" type=\"s:integer\"/>
                </s:extension>
              </s:simpleContent>
            </s:complexType>
          </s:element>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variableName\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variableDescription\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"valueType\" type=\"s1:valueTypeEnum\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"dataType\" type=\"s1:dataTypeEnum\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"generalCategory\" type=\"s1:generalCategoryEnum\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"sampleMedium\" type=\"s1:SampleMediumEnum\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"units\">
            <s:complexType>
              <s:simpleContent>
                <s:extension base=\"s:string\">
                  <s:attribute name=\"unitsAbbreviation\" type=\"s:normalizedString\"/>
                  <s:attribute name=\"unitsCode\" type=\"s:token\"/>
                  <s:attribute name=\"unitsType\" type=\"s1:UnitsTypeEnum\"/>
                </s:extension>
              </s:simpleContent>
            </s:complexType>
          </s:element>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"options\" type=\"s1:ArrayOfOption\"/>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"note\">
            <s:complexType>
              <s:simpleContent>
                <s:extension base=\"s:string\">
                  <s:attribute name=\"type\" type=\"s:string\"/>
                  <s:attribute name=\"href\" type=\"s:string\"/>
                  <s:attribute name=\"title\" type=\"s:string\"/>
                  <s:attribute name=\"show\" type=\"s:string\"/>
                </s:extension>
              </s:simpleContent>
            </s:complexType>
          </s:element>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"related\">
            <s:complexType>
              <s:sequence>
                <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"parentID\">
                  <s:complexType>
                    <s:simpleContent>
                      <s:extension base=\"s:string\">
                        <s:attribute name=\"network\" type=\"s:string\"/>
                        <s:attribute name=\"vocabulary\" type=\"s:string\"/>
                        <s:attribute name=\"default\" type=\"s:boolean\"/>
                      </s:extension>
                    </s:simpleContent>
                  </s:complexType>
                </s:element>
                <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"relatedID\">
                  <s:complexType>
                    <s:simpleContent>
                      <s:extension base=\"s:string\">
                        <s:attribute name=\"network\" type=\"s:string\"/>
                        <s:attribute name=\"vocabulary\" type=\"s:string\"/>
                        <s:attribute name=\"default\" type=\"s:boolean\"/>
                      </s:extension>
                    </s:simpleContent>
                  </s:complexType>
                </s:element>
              </s:sequence>
            </s:complexType>
          </s:element>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"extension\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"NoDataValue\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"timeSupport\">
            <s:complexType>
              <s:sequence>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"unit\" type=\"s1:UnitsType\"/>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"timeInterval\" type=\"s:int\"/>
              </s:sequence>
              <s:attribute name=\"isRegular\" type=\"s:boolean\"/>
            </s:complexType>
          </s:element>
        </s:sequence>
        <s:attribute name=\"oid\" type=\"s:normalizedString\"/>
        <s:attribute name=\"metadataDateTime\" type=\"s:dateTime\"/>
      </s:complexType>
      <s:simpleType name=\"valueTypeEnum\">
        <s:restriction base=\"s:string\">
          <s:enumeration value=\"Field Observation\"/>
          <s:enumeration value=\"Sample\"/>
          <s:enumeration value=\"Model Simulation Result\"/>
          <s:enumeration value=\"Derived Value\"/>
        </s:restriction>
      </s:simpleType>
      <s:simpleType name=\"generalCategoryEnum\">
        <s:restriction base=\"s:string\">
          <s:enumeration value=\"Water Quality\"/>
          <s:enumeration value=\"Climate\"/>
          <s:enumeration value=\"Hydrology\"/>
          <s:enumeration value=\"Geology\"/>
          <s:enumeration value=\"Biota\"/>
        </s:restriction>
      </s:simpleType>
      <s:simpleType name=\"SampleMediumEnum\">
        <s:restriction base=\"s:string\">
          <s:enumeration value=\"Surface Water\"/>
          <s:enumeration value=\"Ground Water\"/>
          <s:enumeration value=\"Sediment\"/>
          <s:enumeration value=\"Soil\"/>
          <s:enumeration value=\"Air\"/>
          <s:enumeration value=\"Tissue\"/>
          <s:enumeration value=\"Precipitation\"/>
        </s:restriction>
      </s:simpleType>
      <s:simpleType name=\"UnitsTypeEnum\">
        <s:restriction base=\"s:string\">
          <s:enumeration value=\"Angle\"/>
          <s:enumeration value=\"Area\"/>
          <s:enumeration value=\"Dimensionless\"/>
          <s:enumeration value=\"Energy\"/>
          <s:enumeration value=\"Energy Flux\"/>
          <s:enumeration value=\"Flow\"/>
          <s:enumeration value=\"Force\"/>
          <s:enumeration value=\"Frequency\"/>
          <s:enumeration value=\"Length\"/>
          <s:enumeration value=\"Light\"/>
          <s:enumeration value=\"Mass\"/>
          <s:enumeration value=\"Permeability\"/>
          <s:enumeration value=\"Power\"/>
          <s:enumeration value=\"Pressure/Stress\"/>
          <s:enumeration value=\"Resolution\"/>
          <s:enumeration value=\"Scale\"/>
          <s:enumeration value=\"Temperature\"/>
          <s:enumeration value=\"Time\"/>
          <s:enumeration value=\"Velocity\"/>
          <s:enumeration value=\"Volume\"/>
        </s:restriction>
      </s:simpleType>
      <s:complexType name=\"ArrayOfOption\">
        <s:sequence>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"option\">
            <s:complexType>
              <s:simpleContent>
                <s:extension base=\"s:string\">
                  <s:attribute name=\"name\" type=\"s:normalizedString\"/>
                  <s:attribute name=\"optionID\" type=\"s:integer\"/>
                  <s:attribute name=\"optionCode\" type=\"s:token\"/>
                </s:extension>
              </s:simpleContent>
            </s:complexType>
          </s:element>
        </s:sequence>
      </s:complexType>
      <s:complexType name=\"UnitsType\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UnitName\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UnitDescription\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"UnitType\" type=\"s1:UnitsTypeEnum\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"UnitAbbreviation\" type=\"s:string\"/>
        </s:sequence>
        <s:attribute name=\"UnitID\" type=\"s:int\"/>
      </s:complexType>
      <s:complexType name=\"TimePeriodType\"/>
      <s:complexType name=\"TimeSingleType\">
        <s:complexContent mixed=\"false\">
          <s:extension base=\"s1:TimePeriodType\">
            <s:sequence>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"timeSingle\" type=\"s:dateTime\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"beginDateTime\" type=\"s:dateTime\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"endDateTime\" type=\"s:dateTime\"/>
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name=\"TimePeriodRealTimeType\">
        <s:complexContent mixed=\"false\">
          <s:extension base=\"s1:TimePeriodType\">
            <s:sequence>
              <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"realTimeDataPeriod\" type=\"s:duration\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"beginDateTime\" type=\"s:dateTime\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"endDateTime\" type=\"s:dateTime\"/>
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name=\"TimeIntervalType\">
        <s:complexContent mixed=\"false\">
          <s:extension base=\"s1:TimePeriodType\">
            <s:sequence>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"beginDateTime\" type=\"s:dateTime\"/>
              <s:element maxOccurs=\"1\" minOccurs=\"1\" name=\"endDateTime\" type=\"s:dateTime\"/>
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name=\"MethodType\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MethodDescription\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MethodLink\" type=\"s:string\"/>
        </s:sequence>
        <s:attribute name=\"methodID\" type=\"s:int\"/>
      </s:complexType>
      <s:complexType name=\"SourceType\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Organization\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SourceDescription\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Metadata\" type=\"s1:MetaDataType\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ContactInformation\" type=\"s1:ContactInformationType\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"SourceLink\" type=\"s:anyURI\"/>
        </s:sequence>
        <s:attribute name=\"sourceID\" type=\"s:int\"/>
      </s:complexType>
      <s:complexType name=\"MetaDataType\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TopicCategory\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Title\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Abstract\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ProfileVersion\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"MetadataLink\" type=\"s:anyURI\"/>
        </s:sequence>
      </s:complexType>
      <s:complexType name=\"ContactInformationType\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"ContactName\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"TypeOfContact\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Phone\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Email\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"Address\"/>
        </s:sequence>
      </s:complexType>
      <s:complexType name=\"QualityControlLevelType\">
        <s:simpleContent>
          <s:extension base=\"s:string\">
            <s:attribute name=\"QualityControlLevelID\" type=\"s:int\"/>
          </s:extension>
        </s:simpleContent>
      </s:complexType>
      <s:complexType name=\"VariablesResponseType\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variables\" type=\"s1:ArrayOfVariableInfoType\"/>
        </s:sequence>
      </s:complexType>
      <s:complexType name=\"ArrayOfVariableInfoType\">
        <s:sequence>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"variable\" type=\"s1:VariableInfoType\"/>
        </s:sequence>
      </s:complexType>
      <s:element name=\"variablesResponse\" type=\"s1:VariablesResponseType\"/>
      <s:complexType name=\"TimeSeriesResponseType\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"queryInfo\" type=\"s1:QueryInfoType\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"timeSeries\" type=\"s1:TimeSeriesType\"/>
        </s:sequence>
      </s:complexType>
      <s:complexType name=\"TimeSeriesType\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"sourceInfo\" type=\"s1:SourceInfoType\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"variable\" type=\"s1:VariableInfoType\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"values\" type=\"s1:TsValuesSingleVariableType\"/>
        </s:sequence>
        <s:attribute name=\"name\" type=\"s:string\"/>
      </s:complexType>
      <s:complexType name=\"TsValuesSingleVariableType\">
        <s:sequence>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"value\" type=\"s1:ValueSingleVariable\"/>
          <s:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"qualifier\">
            <s:complexType>
              <s:simpleContent>
                <s:extension base=\"s:string\">
                  <s:attribute name=\"qualifierCode\" type=\"s:token\"/>
                  <s:attribute name=\"qualifierID\" type=\"s:integer\"/>
                  <s:attribute name=\"oid\" type=\"s:normalizedString\"/>
                  <s:attribute name=\"metadataDateTime\" type=\"s:dateTime\"/>
                  <s:attribute name=\"network\" type=\"s:string\"/>
                  <s:attribute name=\"vocabulary\" type=\"s:string\"/>
                  <s:attribute name=\"default\" type=\"s:boolean\"/>
                </s:extension>
              </s:simpleContent>
            </s:complexType>
          </s:element>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"qualityControlLevel\">
            <s:complexType>
              <s:sequence>
                <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"qualityControlLevelID\" type=\"s:normalizedString\"/>
              </s:sequence>
              <s:attribute name=\"qualityControlLevelCode\" type=\"s:string\"/>
              <s:attribute name=\"oid\" type=\"s:normalizedString\"/>
              <s:attribute name=\"metadataDateTime\" type=\"s:dateTime\"/>
              <s:attribute name=\"network\" type=\"s:string\"/>
              <s:attribute name=\"vocabulary\" type=\"s:string\"/>
              <s:attribute name=\"default\" type=\"s:boolean\"/>
            </s:complexType>
          </s:element>
        </s:sequence>
        <s:attribute name=\"timeZoneShiftApplied\" type=\"s:boolean\"/>
        <s:attribute name=\"unitsAbbreviation\" type=\"s:normalizedString\"/>
        <s:attribute name=\"unitsCode\" type=\"s:token\"/>
        <s:attribute name=\"unitsType\" type=\"s1:UnitsTypeEnum\"/>
        <s:attribute name=\"count\" type=\"s:nonNegativeInteger\"/>
        <s:attribute default=\"false\" name=\"unitsAreConverted\" type=\"s:boolean\"/>
      </s:complexType>
      <s:complexType name=\"ValueSingleVariable\">
        <s:simpleContent>
          <s:extension base=\"s:decimal\">
            <s:attribute name=\"qualifiers\" type=\"s:string\"/>
            <s:attribute name=\"censorCode\" type=\"s1:CensorCodeEnum\"/>
            <s:attribute name=\"dateTime\" type=\"s:dateTime\"/>
            <s:attribute name=\"qualityControlLevel\" type=\"s1:QualityControlLevelEnum\"/>
            <s:attribute name=\"methodID\" type=\"s:string\"/>
            <s:attribute name=\"sourceID\" type=\"s:string\"/>
            <s:attribute name=\"accuracyStdDev\" type=\"s:double\"/>
            <s:attribute name=\"codedVocabulary\" type=\"s:boolean\"/>
            <s:attribute name=\"codedVocabularyTerm\" type=\"s:string\"/>
            <s:attribute name=\"sampleID\" type=\"s:string\"/>
            <s:attribute name=\"offsetValue\" type=\"s:double\"/>
            <s:attribute name=\"offsetUnitsAbbreviation\" type=\"s:normalizedString\"/>
            <s:attribute name=\"offsetDescription\" type=\"s:string\"/>
            <s:attribute name=\"offsetUnitsCode\" type=\"s:normalizedString\"/>
            <s:attribute name=\"oid\" type=\"s:normalizedString\"/>
            <s:attribute name=\"metadataDateTime\" type=\"s:dateTime\"/>
          </s:extension>
        </s:simpleContent>
      </s:complexType>
      <s:simpleType name=\"CensorCodeEnum\">
        <s:restriction base=\"s:string\">
          <s:enumeration value=\"lt\"/>
          <s:enumeration value=\"gt\"/>
          <s:enumeration value=\"nc\"/>
        </s:restriction>
      </s:simpleType>
      <s:simpleType name=\"QualityControlLevelEnum\">
        <s:restriction base=\"s:string\">
          <s:enumeration value=\"Raw data\"/>
          <s:enumeration value=\"Quality controlled data\"/>
          <s:enumeration value=\"Derived products\"/>
          <s:enumeration value=\"Interpreted products\"/>
          <s:enumeration value=\"Knowledge products\"/>
        </s:restriction>
      </s:simpleType>
      <s:element name=\"timeSeriesResponse\" type=\"s1:TimeSeriesResponseType\"/>
    </s:schema>
  </wsdl:types>
  <wsdl:message name=\"GetSitesXmlSoapIn\">
    <wsdl:part element=\"tns:GetSitesXml\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetSitesXmlSoapOut\">
    <wsdl:part element=\"tns:GetSitesXmlResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetSiteInfoSoapIn\">
    <wsdl:part element=\"tns:GetSiteInfo\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetSiteInfoSoapOut\">
    <wsdl:part element=\"tns:GetSiteInfoResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetVariableInfoSoapIn\">
    <wsdl:part element=\"tns:GetVariableInfo\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetVariableInfoSoapOut\">
    <wsdl:part element=\"tns:GetVariableInfoResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetSitesSoapIn\">
    <wsdl:part element=\"tns:GetSites\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetSitesSoapOut\">
    <wsdl:part element=\"tns:GetSitesResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetSiteInfoObjectSoapIn\">
    <wsdl:part element=\"tns:GetSiteInfoObject\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetSiteInfoObjectSoapOut\">
    <wsdl:part element=\"tns:GetSiteInfoObjectResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetVariableInfoObjectSoapIn\">
    <wsdl:part element=\"tns:GetVariableInfoObject\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetVariableInfoObjectSoapOut\">
    <wsdl:part element=\"tns:GetVariableInfoObjectResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetValuesSoapIn\">
    <wsdl:part element=\"tns:GetValues\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetValuesSoapOut\">
    <wsdl:part element=\"tns:GetValuesResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetValuesObjectSoapIn\">
    <wsdl:part element=\"tns:GetValuesObject\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:message name=\"GetValuesObjectSoapOut\">
    <wsdl:part element=\"tns:GetValuesObjectResponse\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:portType name=\"WaterOneFlow\">
    <wsdl:operation name=\"GetSitesXml\">
      <wsdl:documentation xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">Given an array of site numbers, this method returns the site metadata for each one. Send the array of site codes in this format: 'NetworkName:SiteCode'</wsdl:documentation>
      <wsdl:input message=\"tns:GetSitesXmlSoapIn\"/>
      <wsdl:output message=\"tns:GetSitesXmlSoapOut\"/>
    </wsdl:operation>
    <wsdl:operation name=\"GetSiteInfo\">
      <wsdl:documentation xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">Given a site number, this method returns the site's metadata. Send the site code in this format: 'NetworkName:SiteCode'</wsdl:documentation>
      <wsdl:input message=\"tns:GetSiteInfoSoapIn\"/>
      <wsdl:output message=\"tns:GetSiteInfoSoapOut\"/>
    </wsdl:operation>
    <wsdl:operation name=\"GetVariableInfo\">
      <wsdl:documentation xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">Given a variable code, this method returns the variable's name. Pass in the variable in this format: 'NetworkName:Variable'</wsdl:documentation>
      <wsdl:input message=\"tns:GetVariableInfoSoapIn\"/>
      <wsdl:output message=\"tns:GetVariableInfoSoapOut\"/>
    </wsdl:operation>
    <wsdl:operation name=\"GetSites\">
      <wsdl:documentation xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">Given an array of site numbers, this method returns the site metadata for each one. Send the array of site codes in this format: 'NetworkName:SiteCode'</wsdl:documentation>
      <wsdl:input message=\"tns:GetSitesSoapIn\"/>
      <wsdl:output message=\"tns:GetSitesSoapOut\"/>
    </wsdl:operation>
    <wsdl:operation name=\"GetSiteInfoObject\">
      <wsdl:documentation xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">Given a site number, this method returns the site's metadata. Send the site code in this format: 'NetworkName:SiteCode'</wsdl:documentation>
      <wsdl:input message=\"tns:GetSiteInfoObjectSoapIn\"/>
      <wsdl:output message=\"tns:GetSiteInfoObjectSoapOut\"/>
    </wsdl:operation>
    <wsdl:operation name=\"GetVariableInfoObject\">
      <wsdl:documentation xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">Given a variable code, this method returns the variable's siteName. Pass in the variable in this format: 'NetworkName:Variable'</wsdl:documentation>
      <wsdl:input message=\"tns:GetVariableInfoObjectSoapIn\"/>
      <wsdl:output message=\"tns:GetVariableInfoObjectSoapOut\"/>
    </wsdl:operation>
    <wsdl:operation name=\"GetValues\">
      <wsdl:documentation xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">Given a site number, a variable, a start date, and an end date, this method returns a time series. Pass in the sitecode and variable in this format: 'NetworkName:SiteCode' and 'NetworkName:Variable'</wsdl:documentation>
      <wsdl:input message=\"tns:GetValuesSoapIn\"/>
      <wsdl:output message=\"tns:GetValuesSoapOut\"/>
    </wsdl:operation>
    <wsdl:operation name=\"GetValuesObject\">
      <wsdl:documentation xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">Given a site number, a variable, a start date, and an end date, this method returns a time series. Pass in the sitecode and variable in this format: 'NetworkName:SiteCode' and 'NetworkName:Variable'</wsdl:documentation>
      <wsdl:input message=\"tns:GetValuesObjectSoapIn\"/>
      <wsdl:output message=\"tns:GetValuesObjectSoapOut\"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name=\"WaterOneFlow\" type=\"tns:WaterOneFlow\">
    <soap:binding transport=\"http://schemas.xmlsoap.org/soap/http\"/>
    <wsdl:operation name=\"GetSitesXml\">
      <soap:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetSitesXml\" style=\"document\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetSiteInfo\">
      <soap:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetSiteInfo\" style=\"document\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetVariableInfo\">
      <soap:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetVariableInfo\" style=\"document\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetSites\">
      <soap:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetSites\" style=\"document\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetSiteInfoObject\">
      <soap:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetSiteInfoObject\" style=\"document\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetVariableInfoObject\">
      <soap:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetVariableInfoObject\" style=\"document\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetValues\">
      <soap:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetValues\" style=\"document\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetValuesObject\">
      <soap:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetValuesObject\" style=\"document\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name=\"WaterOneFlow1\" type=\"tns:WaterOneFlow\">
    <soap12:binding transport=\"http://schemas.xmlsoap.org/soap/http\"/>
    <wsdl:operation name=\"GetSitesXml\">
      <soap12:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetSitesXml\" style=\"document\"/>
      <wsdl:input>
        <soap12:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetSiteInfo\">
      <soap12:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetSiteInfo\" style=\"document\"/>
      <wsdl:input>
        <soap12:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetVariableInfo\">
      <soap12:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetVariableInfo\" style=\"document\"/>
      <wsdl:input>
        <soap12:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetSites\">
      <soap12:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetSites\" style=\"document\"/>
      <wsdl:input>
        <soap12:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetSiteInfoObject\">
      <soap12:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetSiteInfoObject\" style=\"document\"/>
      <wsdl:input>
        <soap12:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetVariableInfoObject\">
      <soap12:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetVariableInfoObject\" style=\"document\"/>
      <wsdl:input>
        <soap12:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetValues\">
      <soap12:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetValues\" style=\"document\"/>
      <wsdl:input>
        <soap12:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name=\"GetValuesObject\">
      <soap12:operation soapAction=\"http://www.cuahsi.org/his/1.0/ws/GetValuesObject\" style=\"document\"/>
      <wsdl:input>
        <soap12:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name=\"WaterOneFlow\">
    <wsdl:documentation xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\">&lt;div&gt;&lt;strong&gt;Developmental service. This service is internal CUAHSI use, and evaluation.&lt;/strong&gt;&lt;/div&gt;</wsdl:documentation>
    <wsdl:port binding=\"tns:WaterOneFlow\" name=\"WaterOneFlow\">
      <soap:address location=\"http://his.crwr.utexas.edu/tpwd/cuahsi_1_0.asmx\"/>
    </wsdl:port>
    <wsdl:port binding=\"tns:WaterOneFlow1\" name=\"WaterOneFlow1\">
      <soap12:address location=\"http://his.crwr.utexas.edu/tpwd/cuahsi_1_0.asmx\"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>"""

    def __init__(self, post='/tpwd/cuahsi_1_0.asmx', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_GetSitesXml(self, ps):
        self.request = ps.Parse(GetSitesXmlSoapIn.typecode)
        return GetSitesXmlSoapOut()

    soapAction['http://www.cuahsi.org/his/1.0/ws/GetSitesXml'] = 'soap_GetSitesXml'
    root[(GetSitesXmlSoapIn.typecode.nspname,GetSitesXmlSoapIn.typecode.pname)] = 'soap_GetSitesXml'

    def soap_GetSiteInfo(self, ps):
        self.request = ps.Parse(GetSiteInfoSoapIn.typecode)
        return GetSiteInfoSoapOut()

    soapAction['http://www.cuahsi.org/his/1.0/ws/GetSiteInfo'] = 'soap_GetSiteInfo'
    root[(GetSiteInfoSoapIn.typecode.nspname,GetSiteInfoSoapIn.typecode.pname)] = 'soap_GetSiteInfo'

    def soap_GetVariableInfo(self, ps):
        self.request = ps.Parse(GetVariableInfoSoapIn.typecode)
        return GetVariableInfoSoapOut()

    soapAction['http://www.cuahsi.org/his/1.0/ws/GetVariableInfo'] = 'soap_GetVariableInfo'
    root[(GetVariableInfoSoapIn.typecode.nspname,GetVariableInfoSoapIn.typecode.pname)] = 'soap_GetVariableInfo'

    def soap_GetSites(self, ps):
        self.request = ps.Parse(GetSitesSoapIn.typecode)
        return GetSitesSoapOut()

    soapAction['http://www.cuahsi.org/his/1.0/ws/GetSites'] = 'soap_GetSites'
    root[(GetSitesSoapIn.typecode.nspname,GetSitesSoapIn.typecode.pname)] = 'soap_GetSites'

    def soap_GetSiteInfoObject(self, ps):
        self.request = ps.Parse(GetSiteInfoObjectSoapIn.typecode)
        return GetSiteInfoObjectSoapOut()

    soapAction['http://www.cuahsi.org/his/1.0/ws/GetSiteInfoObject'] = 'soap_GetSiteInfoObject'
    root[(GetSiteInfoObjectSoapIn.typecode.nspname,GetSiteInfoObjectSoapIn.typecode.pname)] = 'soap_GetSiteInfoObject'

    def soap_GetVariableInfoObject(self, ps):
        self.request = ps.Parse(GetVariableInfoObjectSoapIn.typecode)
        return GetVariableInfoObjectSoapOut()

    soapAction['http://www.cuahsi.org/his/1.0/ws/GetVariableInfoObject'] = 'soap_GetVariableInfoObject'
    root[(GetVariableInfoObjectSoapIn.typecode.nspname,GetVariableInfoObjectSoapIn.typecode.pname)] = 'soap_GetVariableInfoObject'

    def soap_GetValues(self, ps):
        self.request = ps.Parse(GetValuesSoapIn.typecode)
        return GetValuesSoapOut()

    soapAction['http://www.cuahsi.org/his/1.0/ws/GetValues'] = 'soap_GetValues'
    root[(GetValuesSoapIn.typecode.nspname,GetValuesSoapIn.typecode.pname)] = 'soap_GetValues'

    def soap_GetValuesObject(self, ps):
        self.request = ps.Parse(GetValuesObjectSoapIn.typecode)
        return GetValuesObjectSoapOut()

    soapAction['http://www.cuahsi.org/his/1.0/ws/GetValuesObject'] = 'soap_GetValuesObject'
    root[(GetValuesObjectSoapIn.typecode.nspname,GetValuesObjectSoapIn.typecode.pname)] = 'soap_GetValuesObject'

    def soap_GetSitesXml(self, ps):
        self.request = ps.Parse(GetSitesXmlSoapIn.typecode)
        return GetSitesXmlSoapOut()

    soapAction[''] = 'soap_GetSitesXml'
    root[(GetSitesXmlSoapIn.typecode.nspname,GetSitesXmlSoapIn.typecode.pname)] = 'soap_GetSitesXml'

    def soap_GetSiteInfo(self, ps):
        self.request = ps.Parse(GetSiteInfoSoapIn.typecode)
        return GetSiteInfoSoapOut()

    soapAction[''] = 'soap_GetSiteInfo'
    root[(GetSiteInfoSoapIn.typecode.nspname,GetSiteInfoSoapIn.typecode.pname)] = 'soap_GetSiteInfo'

    def soap_GetVariableInfo(self, ps):
        self.request = ps.Parse(GetVariableInfoSoapIn.typecode)
        return GetVariableInfoSoapOut()

    soapAction[''] = 'soap_GetVariableInfo'
    root[(GetVariableInfoSoapIn.typecode.nspname,GetVariableInfoSoapIn.typecode.pname)] = 'soap_GetVariableInfo'

    def soap_GetSites(self, ps):
        self.request = ps.Parse(GetSitesSoapIn.typecode)
        return GetSitesSoapOut()

    soapAction[''] = 'soap_GetSites'
    root[(GetSitesSoapIn.typecode.nspname,GetSitesSoapIn.typecode.pname)] = 'soap_GetSites'

    def soap_GetSiteInfoObject(self, ps):
        self.request = ps.Parse(GetSiteInfoObjectSoapIn.typecode)
        return GetSiteInfoObjectSoapOut()

    soapAction[''] = 'soap_GetSiteInfoObject'
    root[(GetSiteInfoObjectSoapIn.typecode.nspname,GetSiteInfoObjectSoapIn.typecode.pname)] = 'soap_GetSiteInfoObject'

    def soap_GetVariableInfoObject(self, ps):
        self.request = ps.Parse(GetVariableInfoObjectSoapIn.typecode)
        return GetVariableInfoObjectSoapOut()

    soapAction[''] = 'soap_GetVariableInfoObject'
    root[(GetVariableInfoObjectSoapIn.typecode.nspname,GetVariableInfoObjectSoapIn.typecode.pname)] = 'soap_GetVariableInfoObject'

    def soap_GetValues(self, ps):
        self.request = ps.Parse(GetValuesSoapIn.typecode)
        return GetValuesSoapOut()

    soapAction[''] = 'soap_GetValues'
    root[(GetValuesSoapIn.typecode.nspname,GetValuesSoapIn.typecode.pname)] = 'soap_GetValues'

    def soap_GetValuesObject(self, ps):
        self.request = ps.Parse(GetValuesObjectSoapIn.typecode)
        return GetValuesObjectSoapOut()

    soapAction[''] = 'soap_GetValuesObject'
    root[(GetValuesObjectSoapIn.typecode.nspname,GetValuesObjectSoapIn.typecode.pname)] = 'soap_GetValuesObject'

