################################################## 
# WaterOneFlow_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from WaterOneFlow_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class WaterOneFlowLocator:
    WaterOneFlow_address = "http://his.crwr.utexas.edu/tpwd/cuahsi_1_0.asmx"
    def getWaterOneFlowAddress(self):
        return WaterOneFlowLocator.WaterOneFlow_address
    def getWaterOneFlow(self, url=None, **kw):
        return WaterOneFlowSOAP(url or WaterOneFlowLocator.WaterOneFlow_address, **kw)

# Methods
class WaterOneFlowSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: GetSitesXml
    def GetSitesXml(self, request):
        if isinstance(request, GetSitesXmlSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.cuahsi.org/his/1.0/ws/GetSitesXml", **kw)
        # no output wsaction
        response = self.binding.Receive(GetSitesXmlSoapOut.typecode)
        return response

    # op: GetSiteInfo
    def GetSiteInfo(self, request):
        if isinstance(request, GetSiteInfoSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.cuahsi.org/his/1.0/ws/GetSiteInfo", **kw)
        # no output wsaction
        response = self.binding.Receive(GetSiteInfoSoapOut.typecode)
        return response

    # op: GetVariableInfo
    def GetVariableInfo(self, request):
        if isinstance(request, GetVariableInfoSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.cuahsi.org/his/1.0/ws/GetVariableInfo", **kw)
        # no output wsaction
        response = self.binding.Receive(GetVariableInfoSoapOut.typecode)
        return response

    # op: GetSites
    def GetSites(self, request):
        if isinstance(request, GetSitesSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.cuahsi.org/his/1.0/ws/GetSites", **kw)
        # no output wsaction
        response = self.binding.Receive(GetSitesSoapOut.typecode)
        return response

    # op: GetSiteInfoObject
    def GetSiteInfoObject(self, request):
        if isinstance(request, GetSiteInfoObjectSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.cuahsi.org/his/1.0/ws/GetSiteInfoObject", **kw)
        # no output wsaction
        response = self.binding.Receive(GetSiteInfoObjectSoapOut.typecode)
        return response

    # op: GetVariableInfoObject
    def GetVariableInfoObject(self, request):
        if isinstance(request, GetVariableInfoObjectSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.cuahsi.org/his/1.0/ws/GetVariableInfoObject", **kw)
        # no output wsaction
        response = self.binding.Receive(GetVariableInfoObjectSoapOut.typecode)
        return response

    # op: GetValues
    def GetValues(self, request):
        if isinstance(request, GetValuesSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.cuahsi.org/his/1.0/ws/GetValues", **kw)
        # no output wsaction
        response = self.binding.Receive(GetValuesSoapOut.typecode)
        return response

    # op: GetValuesObject
    def GetValuesObject(self, request):
        if isinstance(request, GetValuesObjectSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.cuahsi.org/his/1.0/ws/GetValuesObject", **kw)
        # no output wsaction
        response = self.binding.Receive(GetValuesObjectSoapOut.typecode)
        return response

GetSitesXmlSoapIn = ns0.GetSitesXml_Dec().pyclass

GetSitesXmlSoapOut = ns0.GetSitesXmlResponse_Dec().pyclass

GetSiteInfoSoapIn = ns0.GetSiteInfo_Dec().pyclass

GetSiteInfoSoapOut = ns0.GetSiteInfoResponse_Dec().pyclass

GetVariableInfoSoapIn = ns0.GetVariableInfo_Dec().pyclass

GetVariableInfoSoapOut = ns0.GetVariableInfoResponse_Dec().pyclass

GetSitesSoapIn = ns0.GetSites_Dec().pyclass

GetSitesSoapOut = ns0.GetSitesResponse_Dec().pyclass

GetSiteInfoObjectSoapIn = ns0.GetSiteInfoObject_Dec().pyclass

GetSiteInfoObjectSoapOut = ns0.GetSiteInfoObjectResponse_Dec().pyclass

GetVariableInfoObjectSoapIn = ns0.GetVariableInfoObject_Dec().pyclass

GetVariableInfoObjectSoapOut = ns0.GetVariableInfoObjectResponse_Dec().pyclass

GetValuesSoapIn = ns0.GetValues_Dec().pyclass

GetValuesSoapOut = ns0.GetValuesResponse_Dec().pyclass

GetValuesObjectSoapIn = ns0.GetValuesObject_Dec().pyclass

GetValuesObjectSoapOut = ns0.GetValuesObjectResponse_Dec().pyclass
